### ISSUE TITLE
AuxAccumulator resetting variable value on each step 

### ISSUE THREAD

**Issue by gsgall** [idaholab/fenix#14]
## Reason
For proper charge mapping the aux accumulator needs to reset the value of the aux variable on each time step

## Design 
In the constructor the AuxAccumulator will set the value of the AuxVariable to 0. 

## Impact
This will enable proper charge mapping from rays to the finite element mesh

**Comment by cticenhour** [comment]
Please add a Design section as well to complete the template.

**Comment by gsgall** [comment]
Done @cticenhour

**Comment by cticenhour** [comment]
Thanks!
